# ==============================================
# Pre-commit Configuration
# ==============================================
# Runs automatically on every git commit
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # -------------------------------------------------
  # General File Checks
  # -------------------------------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
      - id: check-json
        name: Check JSON syntax
      - id: check-toml
        name: Check TOML syntax
      - id: check-added-large-files
        name: Check for large files (>500KB)
        args: ['--maxkb=500']
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']
      - id: detect-private-key
        name: Detect private keys

  # -------------------------------------------------
  # Python - Ruff (Linting & Import Sorting)
  # -------------------------------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      # Run linter
      - id: ruff
        name: Ruff linter
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
      # Run formatter
      - id: ruff-format
        name: Ruff formatter
        types_or: [python, pyi]

  # -------------------------------------------------
  # Python - Black (Code Formatting) [OPTIONAL - Use if you prefer Black over Ruff format]
  # -------------------------------------------------
  # Uncomment if you want to use Black instead of Ruff format
  # - repo: https://github.com/psf/black
  #   rev: 24.1.1
  #   hooks:
  #     - id: black
  #       name: Black formatter
  #       language_version: python3.11

  # -------------------------------------------------
  # Python - Security Checks
  # -------------------------------------------------
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        name: Security linter
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']
        exclude: ^tests/

  # -------------------------------------------------
  # YAML Formatting
  # -------------------------------------------------
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Prettier formatter
        types_or: [yaml, markdown, json]
        exclude: ^(\.venv|venv|node_modules)/

  # -------------------------------------------------
  # Python - Type Checking (Optional)
  # -------------------------------------------------
  # Uncomment to enable MyPy type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       name: MyPy type checker
  #       additional_dependencies: [types-PyYAML, types-requests]
  #       args: [--ignore-missing-imports]

# Global settings
default_language_version:
  python: python3.11

# Performance settings
default_stages: [commit]
fail_fast: false

# File exclusions
exclude: |
  (?x)^(
      \.git/|
      \.venv/|
      venv/|
      __pycache__/|
      \.pytest_cache/|
      \.mypy_cache/|
      \.ruff_cache/|
      build/|
      dist/|
      \.eggs/|
      outputs/|
      logs/
  )
