# Cursor / Claude Subagents Configuration (Starter)
# Minimal defaults — keep lightweight and human-readable.

defaults:
  max_parallel_research: 3
  historian_snapshot_loc_threshold: 150
  ask_before_overwrite: true
  doc_domains_priority:
    - official
    - github
    - trusted-blogs

triggers:
  explorer:
    files_threshold: 2
    loc_threshold: 150
  research_documenter:
    require_for_external_api: true
    require_for_major_version_bump: true
  historian:
    on_end_of_block: true
    on_prd_change: true

preferences:
  planning_style: "sequential-modular"
  documentation_level: "brief-but-consistent"
  tone: "conversational, educational, data-backed"
  explain_reasoning: true
  show_progress: true

# Claude should load this config automatically on startup
# and adapt behaviour of subagents based on these preferences.
