# ==============================================
# Project Plan Template (v1.1)
# Used by Planner Agent for project scaffolding
# ==============================================

meta:
  title: "{{ project_title }}"
  author: "{{ author }}"
  date_created: "{{ date_created }}"
  version: "1.0"
  status: "draft"  # draft | active | archived

project:
  overview:
    summary: "{{ project_summary }}"
    goals:
      - "{{ goal_1 }}"
      - "{{ goal_2 }}"
      - "{{ goal_3 }}"
    scope:
      include:
        - "{{ in_scope_1 }}"
        - "{{ in_scope_2 }}"
        - "{{ in_scope_3 }}"
      exclude:
        - "{{ out_of_scope_1 }}"
        - "{{ out_of_scope_2 }}"
    stakeholders:
      - name: "{{ stakeholder_1_name }}"
        role: "{{ stakeholder_1_role }}"
        responsibility: "{{ stakeholder_1_responsibility }}"
      - name: "{{ stakeholder_2_name }}"
        role: "{{ stakeholder_2_role }}"
        responsibility: "{{ stakeholder_2_responsibility }}"

objectives:
  - id: "OBJ-001"
    description: "{{ objective_1_description }}"
    success_metric: "{{ objective_1_metric }}"
    priority: "high"  # high | medium | low
  
  - id: "OBJ-002"
    description: "{{ objective_2_description }}"
    success_metric: "{{ objective_2_metric }}"
    priority: "medium"

milestones:
  - id: "M1"
    name: "{{ milestone_1_name }}"
    description: "{{ milestone_1_description }}"
    start_date: "{{ milestone_1_start }}"
    end_date: "{{ milestone_1_end }}"
    duration_days: {{ milestone_1_duration }}
    dependencies: []
  
  - id: "M2"
    name: "{{ milestone_2_name }}"
    description: "{{ milestone_2_description }}"
    start_date: "{{ milestone_2_start }}"
    end_date: "{{ milestone_2_end }}"
    duration_days: {{ milestone_2_duration }}
    dependencies:
      - "M1"
  
  - id: "M3"
    name: "{{ milestone_3_name }}"
    description: "{{ milestone_3_description }}"
    start_date: "{{ milestone_3_start }}"
    end_date: "{{ milestone_3_end }}"
    duration_days: {{ milestone_3_duration }}
    dependencies:
      - "M2"

risks:
  - id: "RSK-001"
    description: "{{ risk_1_description }}"
    impact: "high"  # high | medium | low
    likelihood: "medium"  # high | medium | low
    mitigation_strategy: "{{ risk_1_mitigation }}"
  
  - id: "RSK-002"
    description: "{{ risk_2_description }}"
    impact: "medium"
    likelihood: "medium"
    mitigation_strategy: "{{ risk_2_mitigation }}"

resources:
  people:
    - name: "{{ person_1_name }}"
      role: "{{ person_1_role }}"
      availability: "{{ person_1_availability }}"
    
    - name: "{{ person_2_name }}"
      role: "{{ person_2_role }}"
      availability: "{{ person_2_availability }}"
  
  tools:
    - name: "{{ tool_1_name }}"
      purpose: "{{ tool_1_purpose }}"
      license: "{{ tool_1_license }}"
    
    - name: "{{ tool_2_name }}"
      purpose: "{{ tool_2_purpose }}"
      license: "{{ tool_2_license }}"

success_criteria:
  - metric: "{{ success_metric_1 }}"
    target: "{{ success_target_1 }}"
    method: "{{ success_method_1 }}"
  
  - metric: "{{ success_metric_2 }}"
    target: "{{ success_target_2 }}"
    method: "{{ success_method_2 }}"

notes:
  - "{{ note_1 }}"
  - "{{ note_2 }}"
  - "Generated by Planner Agent v1.1"
  - "Template location: /config/templates/project_plan.yaml"
